# Generated by Django 5.1 on 2024-09-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_initial'),
        ('patients', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='users.doctormodel', verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/', verbose_name='Documentos'),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patientmodel', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='prescription',
            field=models.TextField(verbose_name='Prescrição'),
        ),
    ]
