# Generated by Django 5.1 on 2024-09-08 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='appointments_doctor', to='users.doctormodel', verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='appointments_patient', to='patients.patientmodel', verbose_name='Paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentmodel',
            unique_together={('patient', 'appointment_date')},
        ),
    ]
